#!/bin/sh -e
# Git pre-commit hook. Use with a symlink:
# $ ln -sf ../../pre-commit .git/hooks/pre-commit

# Only difference from ci-build.sh is that black only checks formatting

export PIPENV_VERBOSITY=-1 

cd $(git rev-parse --show-toplevel)

echo '>>> Run Black'
pipenv run black --check src

echo '>>> Run Pylint'
pipenv run pylint -E src/

echo '>>> Run Mypy'
pipenv run mypy src

echo '>>>  Run Pytest'
pipenv run pytest -v --doctest-modules src
